# Generated by Django 4.2.6 on 2026-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_remove_profile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='indoor_humidity',
            field=models.FloatField(blank=True, help_text='Humedad relativa promedio del espacio de cultivo indoor (%)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='indoor_temperature',
            field=models.FloatField(blank=True, help_text='Temperatura promedio del espacio de cultivo indoor (°C)', null=True),
        ),
    ]
