# Generated by Django 4.2.6 on 2026-01-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_profile_indoor_humidity_profile_indoor_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='indoor_humidity',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='indoor_temperature',
        ),
    ]
