# Generated by Django 4.2.27 on 2026-01-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_remove_profile_indoor_humidity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_calendar_event_time',
            field=models.TimeField(default='09:00:00', help_text='Hora del día preferida para los eventos de calendario'),
        ),
    ]
