databases:
  # Servicio de la base de datos PostgreSQL
  - name: riegum-db
    databaseName: riegum_db
    user: riegum_user
    plan: free # Plan gratuito para pruebas, puedes cambiar a 'starter' para producción pequeña

services:
  # Servicio de la aplicación web Django
  - type: web
    name: riegum-web
    env: python
    # Render inyectará la variable de entorno DATABASE_URL automáticamente
    # gracias a la sección 'envVars' de abajo, que conecta con la base de datos.

    # Configuración del dominio personalizado
    domains:
      - riegum.com

    # Comando para instalar dependencias y recolectar archivos estáticos
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput # Recolecta archivos estáticos
      python manage.py migrate             # Aplica las migraciones de la base de datos

    # Comando para iniciar el servidor Gunicorn
    # 'riego_indoor' es el nombre de tu carpeta principal de Django
    startCommand: gunicorn --workers 4 --chdir riego_indoor riego_indoor.wsgi:application

    # Variables de entorno para la aplicación web
    envVars:
      - key: SECRET_KEY
        sync: false # No sincronizar con el repositorio, se establecerá en el dashboard de Render
      - key: DATABASE_URL
        fromDatabase:
          name: riegum-db
          property: connectionString
      - key: DEBUG
        value: "False" # Siempre False en producción
      - key: RENDER_EXTERNAL_HOSTNAME
        value: ${RENDER_EXTERNAL_HOSTNAME} # Render inyecta este valor automáticamente
      - key: GOOGLE_MAPS_API_KEY
        sync: false # No sincronizar, se establecerá en el dashboard de Render
      - key: GOOGLE_CLIENT_ID
        sync: false # No sincronizar, se establecerá en el dashboard de Render
      - key: GOOGLE_CLIENT_SECRET
        sync: false # No sincronizar, se establecerá en el dashboard de Render
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
    # Puedes añadir más variables de entorno aquí si las necesitas