# Generated by Django 4.2.6 on 2025-10-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_profile_access_token_profile_refresh_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token_expiry',
        ),
        migrations.AddField(
            model_name='profile',
            name='google_access_token',
            field=models.TextField(blank=True, help_text='Token de acceso de Google OAuth2', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_refresh_token',
            field=models.TextField(blank=True, help_text='Token de refresco de Google OAuth2', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, help_text='Fecha de expiración del token de Google', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='calendar_id',
            field=models.CharField(blank=True, help_text='Email o ID del calendario de Google donde crear eventos', max_length=255, null=True),
        ),
    ]
