# Generated by Django 4.2.6 on 2025-09-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_rename_tamano_maceta_planta_tamano_maceta_litros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='tamano_planta',
            field=models.CharField(choices=[('Pequeña', 'Pequeña'), ('Mediana', 'Mediana'), ('Grande', 'Grande')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tipo_planta',
            field=models.CharField(choices=[('Auto', 'Autofloreciente'), ('Foto', 'Fotoperiódica')], max_length=10),
        ),
    ]
