# Generated by Django 5.2.5 on 2025-08-18 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personalizado', models.CharField(max_length=100)),
                ('tipo_planta', models.CharField(choices=[('auto', 'Autofloreciente'), ('foto', 'Fotoperiódica')], max_length=10)),
                ('tamano_planta', models.CharField(choices=[('pequeña', 'Pequeña'), ('mediana', 'Mediana'), ('grande', 'Grande')], max_length=10)),
                ('tamano_maceta', models.FloatField(help_text='Tamaño en litros')),
                ('fecha_ultimo_riego', models.DateField()),
                ('en_floracion', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad_agua_ml', models.IntegerField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riegos', to='plantas.planta')),
            ],
        ),
    ]
