# Generated by Django 5.2.5 on 2025-08-19 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='tamano_maceta',
            new_name='tamano_maceta_litros',
        ),
    ]
