# Generated by Django 4.2.6 on 2025-10-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_alter_planta_tamano_planta_alter_planta_tipo_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text='ID del evento de Google Calendar para el próximo riego', max_length=255, null=True),
        ),
    ]
