# Generated by Django 4.2.25 on 2025-10-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_planta_google_calendar_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='tamano_maceta_litros',
            field=models.FloatField(default=0.0, help_text='Tamaño en litros'),
        ),
    ]
