# Generated by Django 4.2.6 on 2026-01-25 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_alter_planta_tamano_maceta_litros'),
    ]

    operations = [
        migrations.AddField(
            model_name='riego',
            name='ec_agua',
            field=models.FloatField(blank=True, help_text='Conductividad eléctrica del agua (mS/cm)', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='riego',
            name='ph_agua',
            field=models.FloatField(blank=True, help_text='pH del agua (rango 0-14)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(14.0)]),
        ),
        migrations.AddField(
            model_name='riego',
            name='suplementos_aplicados',
            field=models.TextField(blank=True, help_text='Descripción de suplementos/nutrientes aplicados'),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tamano_maceta_litros',
            field=models.FloatField(default=0.0, help_text='Tamaño en litros (mínimo 1L)', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
