# Generated by Django 4.2.6 on 2026-01-25 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantas', '0006_riego_ec_agua_riego_ph_agua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_promedio', models.FloatField(blank=True, help_text='Temperatura promedio del espacio de cultivo indoor (°C). Rango: -10 a 50°C', null=True, validators=[django.core.validators.MinValueValidator(-10.0), django.core.validators.MaxValueValidator(50.0)])),
                ('humedad_relativa', models.FloatField(blank=True, help_text='Humedad relativa promedio del espacio de cultivo indoor (%). Rango: 0-100%', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_cultivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Usuario',
                'verbose_name_plural': 'Configuraciones de Usuarios',
            },
        ),
    ]
