# Generated by Django 4.2.6 on 2026-01-26 01:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantas', '0007_configuracionusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalidadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_localidad', models.CharField(help_text='Ej: Córdoba, Argentina', max_length=255)),
                ('latitud', models.FloatField(help_text='Latitud de la localidad')),
                ('longitud', models.FloatField(help_text='Longitud de la localidad')),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, recalcula riegos automáticamente')),
                ('ultima_actualizacion_clima', models.DateTimeField(blank=True, help_text='Última vez que se obtuvo el clima', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localidad_outdoor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localidad de Usuario',
                'verbose_name_plural': 'Localidades de Usuarios',
            },
        ),
        migrations.AddField(
            model_name='planta',
            name='tipo_cultivo',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', help_text='Tipo de cultivo: indoor (temp/humedad fijas) u outdoor (clima automático)', max_length=10),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tamano_maceta_litros',
            field=models.FloatField(help_text='Tamaño en litros (mínimo 1L)', validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.CreateModel(
            name='RegistroClima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('temperatura_max', models.FloatField(help_text='Temperatura máxima del día (°C)')),
                ('temperatura_min', models.FloatField(help_text='Temperatura mínima del día (°C)')),
                ('humedad_promedio', models.FloatField(help_text='Humedad relativa promedio (%)')),
                ('precipitacion_mm', models.FloatField(default=0, help_text='Precipitación en milímetros')),
                ('velocidad_viento_kmh', models.FloatField(default=0, help_text='Velocidad del viento (km/h)')),
                ('riegos_recalculados', models.BooleanField(default=False, help_text='Si ya se procesó este registro')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_clima', to='plantas.localidadusuario')),
            ],
            options={
                'verbose_name': 'Registro de Clima',
                'verbose_name_plural': 'Registros de Clima',
                'ordering': ['-fecha'],
                'unique_together': {('localidad', 'fecha')},
            },
        ),
    ]
