# Generated by Django 4.2.27 on 2026-02-09 17:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantas', '0008_localidadusuario_planta_tipo_cultivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='tamano_maceta_litros',
            field=models.FloatField(help_text='Tamaño en litros (mínimo 0.1L)', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre de usuario (guardado por si el usuario se elimina)', max_length=150)),
                ('action', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('REGISTER', 'Registro de usuario'), ('DELETE_ACCOUNT', 'Eliminación de cuenta'), ('CALENDAR_LINK', 'Vinculación de Google Calendar'), ('CALENDAR_UNLINK', 'Desvinculación de Google Calendar'), ('PLANT_CREATE', 'Creación de planta'), ('PLANT_DELETE', 'Eliminación de planta'), ('CONFIG_UPDATE', 'Actualización de configuración'), ('PASSWORD_CHANGE', 'Cambio de contraseña')], db_index=True, help_text='Tipo de acción realizada', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento en que ocurrió la acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent del navegador')),
                ('details', models.JSONField(blank=True, help_text='Detalles adicionales de la acción en formato JSON', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (null si fue eliminado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='plantas_aud_user_id_3df422_idx'), models.Index(fields=['action', '-timestamp'], name='plantas_aud_action_3799b3_idx')],
            },
        ),
    ]
