# Generated by Django 4.2.27 on 2026-02-09 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0009_alter_planta_tamano_maceta_litros_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPlanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_url', models.URLField(help_text='URL pública de la imagen en Google Cloud Storage', max_length=500)),
                ('gcs_blob_name', models.CharField(db_index=True, help_text='Nombre del blob en GCS (para eliminación)', max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de subida de la imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en la galería')),
                ('planta', models.ForeignKey(help_text='Planta a la que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='plantas.planta')),
            ],
            options={
                'verbose_name': 'Imagen de Planta',
                'verbose_name_plural': 'Imágenes de Plantas',
                'ordering': ['orden', '-fecha_subida'],
                'indexes': [models.Index(fields=['planta', 'orden'], name='plantas_ima_planta__5ecbb1_idx'), models.Index(fields=['planta', '-fecha_subida'], name='plantas_ima_planta__e7ee26_idx')],
            },
        ),
    ]
