# Generated by Django 4.2.27 on 2026-02-11 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0010_imagenplanta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='cantidad_agua_manual_ml',
            field=models.IntegerField(blank=True, help_text="Cantidad de agua en ml (solo para categoría 'Otras'). Rango: 10-10000 ml", null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='planta',
            name='categoria_botanica',
            field=models.CharField(choices=[('Cannabis', 'Cannabis'), ('Otras', 'Otras')], default='Cannabis', help_text='Categoría botánica: Cannabis (cálculo automático) u Otras (valores manuales)', max_length=10),
        ),
        migrations.AddField(
            model_name='planta',
            name='frecuencia_riego_manual',
            field=models.IntegerField(blank=True, help_text="Frecuencia de riego en días (solo para categoría 'Otras'). Rango: 1-30 días", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tipo_planta',
            field=models.CharField(blank=True, choices=[('Auto', 'Autofloreciente'), ('Foto', 'Fotoperiódica')], max_length=10, null=True),
        ),
    ]
